# Generated by Django 6.0.3 on 2026-04-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0011_leadimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='client_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lead',
            name='execution_timeline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='property_type',
            field=models.CharField(blank=True, choices=[('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('4BHK', '4 BHK'), ('8BHK', '8 BHK')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Manual team budget', max_digits=12),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('MISSED_CALL', 'Missed Call'), ('MEETING', 'Meeting'), ('QUOTATION', 'Quotation'), ('DISCUSSION', 'Final Discussion'), ('CLOSED', 'Deal Closed'), ('LOST', 'Deal Lost')], default='NEW', max_length=20),
        ),
    ]
