# Generated by Django 6.0.3 on 2026-04-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0012_lead_client_budget_lead_execution_timeline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='client_budget',
        ),
        migrations.AlterField(
            model_name='lead',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lead',
            name='property_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
