# Generated by Django 6.0.3 on 2026-04-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0013_remove_lead_client_budget_alter_lead_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadimport',
            name='execution_timeline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadimport',
            name='property_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
