# Generated by Django 6.0.3 on 2026-04-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0014_leadimport_execution_timeline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
