# Generated by Django 6.0.3 on 2026-04-23 05:03

import tele_crm.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0015_sitevisit_google_calendar_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='floor_plan_2d',
            field=models.FileField(blank=True, null=True, upload_to=tele_crm.utils.SecureFileUpload('requirements/2d/'), validators=[tele_crm.utils.validate_file_size, tele_crm.utils.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='floor_plan_3d',
            field=models.FileField(blank=True, null=True, upload_to=tele_crm.utils.SecureFileUpload('requirements/3d/'), validators=[tele_crm.utils.validate_file_size, tele_crm.utils.validate_file_extension]),
        ),
    ]
