# Generated by Django 6.0.3 on 2026-04-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_quotation_design_theme_quotation_exclusions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='designer_name',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='project_type',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial')], default='RESIDENTIAL', max_length=20),
        ),
    ]
