# Generated by Django 6.0.3 on 2026-04-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_remove_quotation_designer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialspecification',
            name='quotation',
        ),
        migrations.DeleteModel(
            name='CivilWorkItem',
        ),
        migrations.DeleteModel(
            name='MaterialSpecification',
        ),
    ]
