# Generated by Django 6.0.3 on 2026-04-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_remove_materialspecification_quotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
