# Generated by Django 6.0.3 on 2026-04-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auditlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
